# Generated by Django 4.0.2 on 2023-03-09 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whitelist', '0002_alter_wl_nft_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wl',
        ),
    ]
