# Generated by Django 4.0.2 on 2023-03-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitelist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wl',
            name='nft_address',
            field=models.CharField(help_text='Hold any of these NFT(Moondogs, CorepunksV2,Core Id)Submit wallet address of holding', max_length=50),
        ),
    ]
