# Generated by Django 4.0.2 on 2023-03-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('whitelist', '0003_delete_wl'),
    ]

    operations = [
        migrations.CreateModel(
            name='wl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.CharField(max_length=100)),
                ('metamask', models.CharField(max_length=50)),
                ('nft_address', models.CharField(help_text='Hold any of these NFT(Moondogs, CorepunksV2,Core Id)Submit wallet address of holding', max_length=50)),
                ('follow', models.BooleanField()),
                ('retweet', models.BooleanField()),
            ],
        ),
    ]
